# Generated by Django 3.2.4 on 2021-08-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210814_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='games',
            field=models.ManyToManyField(to='accounts.Game'),
        ),
    ]
