# Generated by Django 3.2.4 on 2021-08-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='games',
            new_name='different_games',
        ),
    ]
