# Generated by Django 3.2.4 on 2021-08-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_games_game_different_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=23, unique=True),
            preserve_default=False,
        ),
    ]
